### ISSUE TITLE
Frontend discussion

### ISSUE THREAD

**Issue by flyingsonu122** [girlscript/Girscript-Community-Website#1]
I want to work on the front end

**Comment by amishaagarwal1998** [comment]
Sure you may start working on it. The frontend is using js. Refer to mov file to know about the front end better

**Comment by n-coder2k** [comment]
I want to work on front end

**Comment by keshavga1209** [comment]
I am also interested in contributing to front end of the website as a GSSOC participant. Can you assign it to me as well?

**Comment by AlacritousCreature** [comment]
Hey! @Rao-DY @milind56! I would like to start working on the frontend.....but it seems that the basic setup isn't done yet for this website. Please make it soon so that we can start working on it. I would like to start contributing by applying a suitable navbar and footer.

**Comment by musk101** [comment]
Hey! @Rao-DY @milind56 @amishaagarwal1998 I have started the basic structure of the website using React and antd library from scratch.

**Comment by amishaagarwal1998** [comment]
Hey! @Rao-DY <https://github.com/Rao-DY> @milind56
<https://github.com/milind56>! Please do the basic step of the website
 It would be easy for us to contribute from there.

**Comment by codewithvk** [comment]
@Everyone Check issue related to your stack and start contributing.

**Comment by Shulabh-968026** [comment]
I would like work on Front End.Can I work on  it.
