### ISSUE TITLE
Add bug and feature template for issues

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#10]
- Template for bug report issue containing all the required the sections like {Current behavior, expected behavior, Related screenshot, Device used, etc}
 - Template for feature request issue containing all the required the sections like Feature description, Related link. screenshot for reference, etc.

**Comment by vedikaag99** [comment]
@codewithvk Can I take up this issue?
Also, do I make seperate PR's for each of them?

**Comment by codewithvk** [comment]
@vedikaag99 Go ahead!

**Comment by vedikaag99** [comment]
@codewithvk do I need to make separate PRs for each of them?

**Comment by codewithvk** [comment]
@vedikaag99 You can!
