### ISSUE TITLE
Add Pull Request template 

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#12]
- A good enough PR template that contains all the required sections including which issue it closes issue number, Feature/Change, Screenshot/Image of Feature

**Comment by cryptofox17** [comment]
Could I work on this please?

**Comment by vedikaag99** [comment]
@codewithvk Can I take up this issue?
I do have one question though. Do I create a `.github` folder and add the template.md there?

**Comment by shreyanshi16** [comment]
I want to work on this issue. Please assign me.

**Comment by codewithvk** [comment]
@cryptofox17, @vedikaag99, @shreyanshi16  We do not assign more than one issue at a time. Kindly complete assigned issue :)

**Comment by flyingsonu122** [comment]
@codewithvk assign this to me

**Comment by codewithvk** [comment]
@flyingsonu122 go ahead!

**Comment by flyingsonu122** [comment]
@codewithvk done #17
