### ISSUE TITLE
[ Open For All ] Home-Page Design Improvement.

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#14]
- You can give suggest a design for the home page and create using designing tools like Figma.
- Below image is the structure/example.

![HomePage](https://user-images.githubusercontent.com/61119120/111269833-16ee7300-8655-11eb-9771-d84e03a5a736.PNG)

- An assigned person can merge PR and add image file in `assets/homepage/<your name>`

**Comment by rutuja2229** [comment]
Do we hae to create same structure using Figma, I a GSSoC2021 participant
, can I work on this issue plz?

**Comment by codewithvk** [comment]
@rutuja2229 You can take ideas from it and create different designs.

**Comment by rutuja2229** [comment]
I will try my best, thank u so much

**Comment by jhasuraj01** [comment]
As this project is open for all can I work for it?

**Comment by ShambhaviSharma0110** [comment]
Hey! I would really like to work on this please allow me to work on this...
-gssoc'21 participant

**Comment by codewithvk** [comment]
> e is the preview 👇

You can create PR according to the given instructions.

**Comment by codewithvk** [comment]
> Hey! I would really like to work on this please allow me to work on this...
> -gssoc'21 participant

Sure! Go ahead.

**Comment by Castella1313** [comment]
@codewithvk if we all would be designing the home page, on what basis a final design for the home page is gonna get selected?

**Comment by jhasuraj01** [comment]
@codewithvk in which folder shall I put my file?

**Comment by codewithvk** [comment]
> @codewithvk if we all would be designing the home page, on what basis a final design for the home page is gonna get selected?


Design select by Project Admin so don't worry just put your design in the Given instruction.

**Comment by codewithvk** [comment]
> @codewithvk in which folder shall I put my file?

`assets/homepage/<your name>/xyz.png`

**Comment by vedikaag99** [comment]
@codewithvk Can I also give this issue a try?

**Comment by codewithvk** [comment]
@vedikaag99 sure! Go ahead.

**Comment by vedikaag99** [comment]
@codewithvk Do I need to show the design here before opening up a PR?

**Comment by kanishkaa24** [comment]
Hello! Can I work on this ?

**Comment by rutuja2229** [comment]
@codewithvk I made PR #52, please review this design.
