### ISSUE TITLE
Contributors Name in Readme

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#15]
- Add dynamic contributor name in Readme File

**Comment by AlacritousCreature** [comment]
Hey! I would like to do it. May I?

**Comment by codewithvk** [comment]
@AlacritousCreature  Go ahead!!

**Comment by AlacritousCreature** [comment]
Hey @codewithvk, is it fine to add kuch contributors section? This one dynamically fetches all contributers from contributor section of a repo.
![Screenshot (455)](https://user-images.githubusercontent.com/58398802/111300980-ae64bd80-8677-11eb-81aa-6769ab450ecf.png)

**Comment by codewithvk** [comment]
@AlacritousCreature Looks good for me. Go ahead!

**Comment by AlacritousCreature** [comment]
okay!
