### ISSUE TITLE
Improvement In Readme

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#16]
- Improve Structure & Design of Readme File.  
 - Create `Contributor ` file, Add how to create pull request for this repo.

**Comment by rutuja2229** [comment]
I a a GSSoC2021 participant, willing to work on this issue can u assign this to me plz?

**Comment by codewithvk** [comment]
@rutuja2229 Go ahead!

**Comment by rutuja2229** [comment]
Thank u so much

**Comment by manognyaa** [comment]
I am a GSSOC'21 participant, Can I also work on this issue ? @codewithvk

**Comment by rutuja2229** [comment]
@manognyaa  I am working on this, but u can improve the structure and design of readme file if u want, I did complete the next part.

**Comment by rutuja2229** [comment]
@codewithvk Can u tell me what exactly u r expecting to add in main readme file? Please

**Comment by codewithvk** [comment]
@rutuja2229 as of now not much needs to improve.
solve below bug.
![Capture](https://user-images.githubusercontent.com/61119120/111407411-c5e48a80-86f9-11eb-92d4-94bf29e942a7.PNG)
if `gif` not working then you can put a link for that.

**Comment by rutuja2229** [comment]
@codewithvk  okay
