### ISSUE TITLE
Designing About Us Section

### ISSUE THREAD

**Issue by Castella1313** [girlscript/Girscript-Community-Website#27]
**Designing About Us Section in home Page**

![Screenshot 2021-03-17 at 5 03 37 PM](https://user-images.githubusercontent.com/53293156/111461316-0e746600-8743-11eb-8c06-7f05e1bc00fb.png)

**Comment by Castella1313** [comment]
@amishaagarwal1998 I'm a GSSOC'21 participant!! May I work on it?

**Comment by codewithvk** [comment]
@Castella1313 Go ahead!

**Comment by codewithvk** [comment]
@Castella1313 Kindly make the design as generalized so we can put it on join us page, newsletter page & about us page can be handle with one component :)

**Comment by kanishkaa24** [comment]
Hello! Can I work on this ?

**Comment by vedikaag99** [comment]
@codewithvk @amishaagarwal1998 is this issue open to grab?
