### ISSUE TITLE
Email Subscription 

### ISSUE THREAD

**Issue by Sapna2001** [girlscript/Girscript-Community-Website#28]
**Is your feature request related to a problem? Please describe.**
![Screenshot from 2021-03-17 23-14-50](https://user-images.githubusercontent.com/56690856/111514144-75ac0d80-8777-11eb-841f-01e469188f27.png)

**Describe the solution you'd like**
I will be creating the email component. 

**Additional context**
I am a GSSOC 2021 participant please assign me this issue.

**Comment by Castella1313** [comment]
I think it would be great if I get to work on it too just in order to keep the background theme same for all the sections(join us, newsletter, about us)!

**Comment by Castella1313** [comment]
@codewithvk May I work on it?

**Comment by codewithvk** [comment]
@Castella1313 @Sapna2001 both can refer #27 issue.
