### ISSUE TITLE
Designing Join Us Section

### ISSUE THREAD

**Issue by Castella1313** [girlscript/Girscript-Community-Website#29]
**Designing Join Us Section**
![Screenshot 2021-03-17 at 5 04 23 PM](https://user-images.githubusercontent.com/53293156/111556389-7319da00-87b0-11eb-9102-4cc898398e0c.png)

**Comment by Castella1313** [comment]
@amishaagarwal1998 May I work on it?

**Comment by codewithvk** [comment]
@Castella1313 makes it generalized in the assigned issue.
