### ISSUE TITLE
Adding a style guide in README.md

### ISSUE THREAD

**Issue by cryptofox17** [girlscript/Girscript-Community-Website#33]
**Is your feature request related to a problem? Please describe.**
Making a website consistent by using the same color scheme and font across every page. 

**Describe the solution you'd like**
I want to make a style guide that will give the hex codes for all the important colors, font style, button style as shown in the mov. 
It will be a PNG image that contains all these information that will also help people choose the right colors quickly and also make the website consistent.

**Describe alternatives you've considered**

**Additional context**

Please assign this issue to me

**Comment by codewithvk** [comment]
@cryptofox17 go ahead!
