### ISSUE TITLE
Update contribute.md in order to guide the designers how to submit their designs

### ISSUE THREAD

**Issue by jhasuraj01** [girlscript/Girscript-Community-Website#34]
# Problem
contribute.md doesn't have much info regarding how to submit our designs. A clarity is needed regarding the folder structure in which designers can submit their designs.

# Solution
Decide the folder structure, sub folder names for all the component and mention that in contribution.md

For Example:
```
|-- Assets
    |-- homepage
    |    |-- your_name
    |         |-- file_name.png
    |         |-- file_name.jpg
    |-- aboutpage
    |    |-- your_name
    |         |-- file_name.png
    |         |-- file_name.jpg
```

**Comment by jhasuraj01** [comment]
@codewithvk Please assign this to me, I am a gssoc'21 participant

**Comment by codewithvk** [comment]
@jhasuraj01 go ahead!

**Comment by jhasuraj01** [comment]
@codewithvk shall I make respective folders for each design components or shall I left this for designers?

**Comment by codewithvk** [comment]
@jhasuraj01 If you create then it would be great.

**Comment by jhasuraj01** [comment]
okay
