### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#35]
**Deliverables**
- Add a Navbar on the Home screen
- Each Button/Link has a hover effect.
- Logo `Assets/GS_logo_black (1).png`

**Sample**
![Capture](https://user-images.githubusercontent.com/61119120/111582707-3b775600-87e1-11eb-9107-ee72a8fd42d3.PNG)

**Additional context**
- Try to make with less external Library.
- Please attach Image/Gif with PR.

**Comment by RuchiGitHu** [comment]
> **Deliverables**
> 
> * Add a Navbar on the Home screen
> * Each Button/Link has a hover effect.
> * Logo `Assets/GS_logo_black (1).png`
> 
> **Sample**
> ![Capture](https://user-images.githubusercontent.com/61119120/111582707-3b775600-87e1-11eb-9107-ee72a8fd42d3.PNG)
> 
> **Additional context**
> 
> * Try to make with less external Library.
> * Please attach Image/Gif with PR.

Hii @codewithvk , I want to solve this issue as I have build some websites with navbar.
Please /assign this issue so that I can learn new things from here in frontend.
Thanks in advance...

**Comment by codewithvk** [comment]
@RuchiGitHu Happy to see you here! 

Go ahead!

**Comment by musk101** [comment]
Hey! can I also work on this issue? @codewithvk

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?

**Comment by codewithvk** [comment]
@RuchiGitHu What's the update? If you don't want to work on it, let me know I will assign you to some other participants.

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu What's the update? If you don't want to work on it, let me know I will assign you to some other participants.

I want to work on it. I have started working on this issue already. Shortly I will update you regarding progress...
Thanks for assigning....

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu Happy to see you here!
> 
> Go ahead!

Hi @codewithvk, Please review my PR and let me know if there is any changes required.
Looking forward for contributing here...
Thanks in advance.

**Comment by nayaldivya** [comment]
Hey @codewithvk, I want to contribute some quality code to the website preferably at back-end , can you please assign me a issue.

**Comment by codewithvk** [comment]
@musk101 Any update from your side?

**Comment by musk101** [comment]
Hello, @codewithvk sorry for replying late actually my exams started.
I will send a pr with all the changes today for sure.

**Comment by musk101** [comment]
Can you please assign it to me again by mistake I clicked on assign from my end.
@codewithvk

**Comment by musk101** [comment]
@codewithvk  I have sent the PR that resolves both the issues #75 and #35 .
