### ISSUE TITLE
Designing Footer Component 

### ISSUE THREAD

**Issue by Castella1313** [girlscript/Girscript-Community-Website#41]
Designing Footer Component

**Comment by Castella1313** [comment]
@codewithvk May I work on it?

**Comment by Castella1313** [comment]
@codewithvk May I work on it?

**Comment by vedikaag99** [comment]
@codewithvk can I Work on this issue?

**Comment by codewithvk** [comment]
@Castella1313 & @vedikaag99  Go ahead!
