### ISSUE TITLE
Readme Links bug

### ISSUE THREAD

**Issue by alkatrivedi** [girlscript/Girscript-Community-Website#42]
**Describe the bug**
Readme has links in the content section but they are not redirecting user to their respective sections. Like on clicking on the Contributors link it is not redirecting user to the contributors section in the readme.

**To Reproduce the Current Behavior**
Steps to reproduce the current behavior:
1. Go to 'Readme.md'
2. Click on 'any link in the content section'
3. See an error(i.e., it is not directing the user to the desired section in the readme.)

**Expected behavior**
On clicking on those links user be should be directed to that particular section in the readme. 

**Related Screenshots**
![Capture](https://user-images.githubusercontent.com/58396306/111823771-5b0a9d80-890b-11eb-8ab6-c38eeb680281.PNG)

On clicking on any of these links error can be seen.

**Additional context**
I am a GSSoC'21 participant and I want to work on this issue. May I work on this issue under GSSoC'21?

**Comment by chandrikadeb7** [comment]
@alkatrivedi You may proceed!

**Comment by alkatrivedi** [comment]
On it. Thank you.
