### ISSUE TITLE
Header / Navbar

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#53]
**Deliverables**
- Add Navbar Component 
- Each Button/Link has a hover effect.
- Logo `Assets/GS_logo_black (1).png`

**Sample**
![Capture](https://user-images.githubusercontent.com/61119120/112249843-787a9700-8c7e-11eb-97fc-ff4385a570c3.PNG)

**Additional context**
- Tech/Framework:- React Js

**Comment by Godwindaniel10** [comment]
hi, I am Godwin, I will be so glad to work to this issue

**Comment by rutuja2229** [comment]
@codewithvk Can I work on this issue? I am GSSoC 2021 participant, plz.

**Comment by codewithvk** [comment]
@Godwindaniel10 Sure Go ahead!

@rutuja2229 You can look up some other issue :)

**Comment by Godwindaniel10** [comment]
@codewithvk thanks, currently on it..

**Comment by Godwindaniel10** [comment]
@codewithvk , there's an issue at hand , sorry this message is coming late .. I can't run the project on my local machine?       I am not a react dev tho, 
I have tried googling ,on how to run It, but failed .I believe you should explain to me how to run on local machine ☑️

**Comment by codewithvk** [comment]
@Godwindaniel10 No problem with this I will explain you.

First, your system needs to install nodejs and npm(Node package manager). So you can google it according to your Operating system and download it.

- After clone this repo on your local machine 
`https://github.com/Godwindaniel10/Girscript-Community-Website.git`
- write command `cd Girscript-Community-Website/frontend/`
- then write command `npm install`. if you find any error in this step then make sure you check your system has node and npm.
- run command `npm start` and you can see output on `http://localhost:3000/`


If you still find any difficulty then let me know.

**Comment by Godwindaniel10** [comment]
well successfully run the browser. but this what I got.

![girlscript browser](https://user-images.githubusercontent.com/54848535/112443697-29e40000-8d45-11eb-805e-3160221e4c13.JPG)

![girlscript cmd](https://user-images.githubusercontent.com/54848535/112443849-513acd00-8d45-11eb-8bec-1d56caca7a71.JPG)

**Comment by codewithvk** [comment]
@Godwindaniel10 Yap that's show your code run successfully.

**Comment by Godwindaniel10** [comment]
ok great

**Comment by Godwindaniel10** [comment]
Good day, I ran into an issue again, after adding the navbar components, coded and styled the navbar, then I got this error message which I have tried all my possible best to fix it, but nothing...


![hook react](https://user-images.githubusercontent.com/54848535/112629058-b537c100-8e2b-11eb-8f8d-a7870505339b.JPG)

**Comment by Godwindaniel10** [comment]
@RituCs I am already working on the issue but am stuck.

@codewithvk I will like you to assign this to @rutuja2229 or @RituCs .   Thank you 😊, so grateful to atleast be part of this conversation 👍👍👍

**Comment by codewithvk** [comment]
@rutuja2229 do you wanna work on this issue?

**Comment by shreyanshi16** [comment]
@codewithvk i would like to work on this issue. Please assign me.

**Comment by rutuja2229** [comment]
> @rutuja2229 do you wanna work on this issue?
@codewithvk I am working on #58  I will try to make PR on that issue and try to switch on this today itself.

**Comment by codewithvk** [comment]
@shreyanshi16 go ahead!
