### ISSUE TITLE
Create About us Section

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#55]
**Deliverables**
- Make Generalized components.
- Also Generalized color as well. (I mean we can pass using props).

**Sample**
![Capture2](https://user-images.githubusercontent.com/61119120/112250630-b88e4980-8c7f-11eb-8f3c-9f2eaeb927b1.PNG)
![Capture6](https://user-images.githubusercontent.com/61119120/112250641-be842a80-8c7f-11eb-8573-b2b72ba29bd0.PNG)
![Capture9](https://user-images.githubusercontent.com/61119120/112250645-c17f1b00-8c7f-11eb-9c09-832b1f978b9c.PNG)

**Additional context**
- Tech/Framework:- React Js

**Comment by shreyanshi16** [comment]
I would like to work on this issue. Please assign me.

**Comment by Shulabh-968026** [comment]
I would like to work on this issue.Can I Work on it.

**Comment by codewithvk** [comment]
@shreyanshi16 go ahed !

**Comment by Castella1313** [comment]
@codewithvk when this issue will be passed on to other participant? After how many days?

**Comment by shreyanshi16** [comment]
Hi @codewithvk does this look good to you? Or is there any changes that I need to do?
![image](https://user-images.githubusercontent.com/53462278/112668793-edb7b900-8e84-11eb-8d9d-80a48741de92.png)
![image](https://user-images.githubusercontent.com/53462278/112668843-f9a37b00-8e84-11eb-86d1-9cf045aba175.png)

**Comment by codewithvk** [comment]
@shreyanshi16 Ya looks good for me :)

Go ahead and make PR.
