### ISSUE TITLE
Mission & Vision Page Component

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#56]
**Deliverables**
- Add Mission & Vision Page's Component.
- Color you can pick from [here](https://github.com/girlscript/Girscript-Community-Website/blob/master/style.md)

**Sample**
![Capture3](https://user-images.githubusercontent.com/61119120/112250867-33576480-8c80-11eb-93db-c6d9020be4b8.PNG)

**Additional context**
- Tech/Framework:- React Js

**Comment by vedikaag99** [comment]
@codewithvk can I work on this?

**Comment by codewithvk** [comment]
@vedikaag99 go ahead!

**Comment by vedikaag99** [comment]
Hi @codewithvk does this look good to you? Or is there any changes that I need to do?

https://user-images.githubusercontent.com/67699840/112451590-b0b3cf80-8d7b-11eb-8f64-01ada97acbe7.mov

**Comment by codewithvk** [comment]
@vedikaag99 LGFM:)

**Comment by jhasuraj01** [comment]
Can I work for this issue?
