### ISSUE TITLE
Add Our Testimonial Component.

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#60]
**Deliverables**
- Add Our Testimonial Component.
- Use Dummy Data.
- Add Hover Effect.

**Sample**
![Capture7](https://user-images.githubusercontent.com/61119120/112251938-2b98bf80-8c82-11eb-9a80-bce14b034046.PNG)

**Additional context**
- Tech/Framework:- React Js

**Comment by shreyanshi16** [comment]
I would like to work on this issue. Please assign me.

**Comment by codewithvk** [comment]
@shreyanshi16 at the same time we assign only one issue. So kindly complete the assigned issue. after you can work on it :)

**Comment by Castella1313** [comment]
@codewithvk may I work on it?

**Comment by codewithvk** [comment]
@Castella1313 we need to code it. Are you interested?

**Comment by Devenkapoor7303** [comment]
Can I work on this issue?

**Comment by Castella1313** [comment]
> @Castella1313 we need to code it. Are you interested?

yes I'm :) please assign it to me

**Comment by codewithvk** [comment]
@Castella1313 No, we don't need to add a button.
