### ISSUE TITLE
Local Installation step for react js.

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#67]
**Deliverables** 
- need Simple and clean local Installation step for Frontend.
- Make a change on `Readme.md`
- Make a change in `frontend/README.md` as well.

**Comment by Castella1313** [comment]
@codewithvk  may I work on it?

**Comment by vedikaag99** [comment]
@codewithvk I'd like to work on this

**Comment by codewithvk** [comment]
@Castella1313 Go ahead!

**Comment by pragati-kumar** [comment]
@codewithvk 'm a GSSOC'21 participant. I would like to contribute to this issue. We could use two headers "installation" and "setup environment".
