### ISSUE TITLE
Improve testimonial section

### ISSUE THREAD

**Issue by Sapna2001** [girlscript/Girscript-Community-Website#69]
**Is your feature request related to a problem? Please describe.**
I would like to bring the testimonial to the center of the page 

**Describe the solution you'd like**
add justify-content property in CSS file

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Original**
![Screenshot from 2021-03-28 18-36-42](https://user-images.githubusercontent.com/56690856/112753442-4e660380-8ff5-11eb-937a-f198cd818db6.png)

**Modified**
![Screenshot from 2021-03-28 18-44-12](https://user-images.githubusercontent.com/56690856/112753585-adc41380-8ff5-11eb-8f12-37fc27488ba9.png)

@codewithvk I am a GSSOC'21 participant. Please assign me this issue.

**Comment by codewithvk** [comment]
@Sapna2001 Go Ahead!
