### ISSUE TITLE
ScrollTop

### ISSUE THREAD

**Issue by Sapna2001** [girlscript/Girscript-Community-Website#74]
**Is your feature request related to a problem? Please describe.**
I would like to add a button to pages so that the top of the page can be reached without manual scrolling

**Describe the solution you'd like**
Create a scroll top button

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Screenshot**
![Screenshot from 2021-03-29 23-29-24](https://user-images.githubusercontent.com/56690856/112880200-c3196a80-90e7-11eb-9bb0-94f3e6f39cf2.png)

@codewithvk I would like to do this as a part of GSSOC 2021.

**Comment by codewithvk** [comment]
@Sapna2001 go ahead!
