### ISSUE TITLE
Adding "Our Impact" and "Our Community" Section

### ISSUE THREAD

**Issue by SharmaTanish** [girlscript/Girscript-Community-Website#78]
**Add Our Impact and Our Community Section**
Hi @codewithvk I am Tanish . As this website is in progress , so I want to contribute in this program by adding above two sections under this issue . Also I have gone through most of opened issues and no one asked you to work on above 2 sections .

**I Want to add interactive sections to this web page**
As you have some a sample preview in video about how these sections look like , I want to make something like that amazing designs sections .

**Additional context**
I have done web development from coding ninjas and have certificate for the same uploaded on linkedIn and also made some amazing projects like Music player project etc (uploaded on linkedIn) . Also I am learning advance web development (back end) currently , so I can also contribute further in this project after this issue as well . I am very hardworking and scored 94.2% in 12th . Before this project I have merged one pull request in Awesome JavaScript projects , solved one issue in Public Lab repository .
LinkedIn profile link - https://www.linkedin.com/in/tanish-a54b771b3
Looking forward for working for this project .
Thank You
Regards

**Comment by SharmaTanish** [comment]
Hello @codewithvk please assign this issue to me , so that I can start working on this . If there is any problem then please let me know !

**Comment by codewithvk** [comment]
@SharmaTanish  Go ahead!

**Comment by Castella1313** [comment]
@codewithvk when this issue will be passed on to other participants ?

**Comment by codewithvk** [comment]
What's the update @SharmaTanish ?

**Comment by SharmaTanish** [comment]
Hi @codewithvk sorry for the late response , actually some tests are going in my college . But don't worry the design is almost ready , I will send you screenshots by **tomorrow** **for sure** !
Thank you for your patience 
Regards

**Comment by SharmaTanish** [comment]
Hi @codewithvk please have a look on the following design and suggest me more changes and work that I should do.
Also please note that these 2 sections I have made are completely responsive !
Thank you 
![Hnet-image (1)](https://user-images.githubusercontent.com/75024552/114698052-453a9d80-9d3c-11eb-9744-868a501fd840.gif)

**Comment by codewithvk** [comment]
Hey @SharmaTanish , Our **Community section** looks good for me but in **our impact** section needs the below changes.
 - In our impact left component's background color is miss-matched, You can use white or something else.
  - In our impact right components are dynamic, not static. You can take reference from [here](https://www.youtube.com/watch?v=-CwzaTKniH4)

Ps:- If you felt like it is hard for you then you can create  PR with the current code. I will create future issue accordingly :)

**Comment by SharmaTanish** [comment]
I will make these changes for sure and send you by tomorrow . Don't worry I will resolve it and yeah please don't hesitate in mentioning changes that you want , I will for sure do that nothing is hard . I want to make this project successful same as you want .
Open source means nothing but working in team as a unit . So don't worry I will do tasks for this project after this issue as well 🙂.

Thank you

**Comment by SharmaTanish** [comment]
Please tell me the values we need to give in pi-chart? Also our impact left component I think white colour will look good only then ! And any other changes?

**Comment by codewithvk** [comment]
> Please tell me the values we need to give in pi-chart? Also our impact left component I think white colour will look good only then ! And any other changes?

You can use any random Value as of now

**Comment by SharmaTanish** [comment]
@codewithvk please review !
![Hnet-image](https://user-images.githubusercontent.com/75024552/114735617-ff450000-9d62-11eb-8d15-7ad6f6b69737.gif)

**Comment by codewithvk** [comment]
@SharmaTanish LGFM :) Make PR.

**Comment by SharmaTanish** [comment]
@codewithvk I am facing this problem in pulling the recent commits from original repository , please guide ?
![git_girlscript](https://user-images.githubusercontent.com/75024552/114751090-569e9c80-9d72-11eb-956f-fe57a16e5937.PNG)

**Comment by codewithvk** [comment]
@SharmaTanish git pull <repository> .

**Comment by SharmaTanish** [comment]
Hi @codewithvk , the 2 sections I added are displaying below footer in current website ! So how do I made these just below MISSION AND VISION Section ?? Please guide ? (And sorry for the above silly mistake I did in git command) 

Thank you
Regards
![Screenshot (1595)](https://user-images.githubusercontent.com/75024552/114837597-82149c00-9df1-11eb-8217-481226591288.png)

**Comment by SharmaTanish** [comment]
Hi @codewithvk , the 2 sections I added are displaying below footer in current website ! So how do I made these just below MISSION AND VISION Section ?? Please guide ? (And sorry for the above silly mistake I did in git command) 

Thank you
Regards
![Screenshot (1595)](https://user-images.githubusercontent.com/75024552/114837597-82149c00-9df1-11eb-8217-481226591288.png)

**Comment by codewithvk** [comment]
> Hi @codewithvk , the 2 sections I added are displaying below footer in current website ! So how do I made these just below MISSION AND VISION Section ?? Please guide ? (And sorry for the above silly mistake I did in git command)
> 
> Thank you
> Regards


If you made PR and visible code by PR, Then I will surely help you, and no worries! we are together for learning :)
