### ISSUE TITLE
(Frontend) Add basic react structure 

### ISSUE THREAD

**Issue by codewithvk** [girlscript/Girscript-Community-Website#8]
- Add initial structure for frontend using react having basic components

**Comment by shreyanshi16** [comment]
I want to work on this issue. Please assign me.

**Comment by codewithvk** [comment]
@shreyanshi16 Go ahead. Please name react app as `client`.

**Comment by musk101** [comment]
Hey! I guess I have already done this part. I just have to rename the app name to client for now it's my-app. @codewithvk

**Comment by codewithvk** [comment]
> t have to rename the app n

I think you made PR without any issue and one of the mentors merge your PR by mistake.
Reason:- Before merging your PR this issue was assigned.

Apologies for this thing, I hope you can cooperate with us. If you want to improve any part of code in codebase, Make sure first open issue rather than directly PR. If you have doubt then you can contact me via discord.

Hope You understand. Keep Contributing!
