### ISSUE TITLE
Adding animation to components 

### ISSUE THREAD

**Issue by Castella1313** [girlscript/Girscript-Community-Website#84]
Adding animations to components 

Like this 

https://user-images.githubusercontent.com/53293156/113879416-1f5f4700-97d8-11eb-8798-196fa53e8a51.mov

**Comment by Castella1313** [comment]
@codewithvk  May I work on this ????

**Comment by codewithvk** [comment]
@Castella1313 As of now we more work on component building.

**Comment by Castella1313** [comment]
@codewithvk okay! Should we close this issue or keep for later?

**Comment by codewithvk** [comment]
@Castella1313 Close is a better opestion.
