### ISSUE TITLE
Navbar improvement

### ISSUE THREAD

**Issue by kumarishalini6** [girlscript/Girscript-Community-Website#86]
I have seen someone is created issue of making HOME,OUR IMAPCT and  OUR COMMUNITY  pages .
so there should be link in navbar that direct render on that pages.
I want to work on this issue under GSSoC'21.

**Comment by codewithvk** [comment]
@kumarishalini6 Do you means, add router?

**Comment by kumarishalini6** [comment]
Yes

**Comment by codewithvk** [comment]
@kumarishalini6 go ahead!

**Comment by kumarishalini6** [comment]
Thanks

**Comment by kumarishalini6** [comment]
I have exam in this week after that I'll work on this issue

**Comment by a-abhinav** [comment]
@codewithvk as previous assignee is busy can I solve this issue this ?

**Comment by kumarishalini6** [comment]
I have send PR please review it.

**Comment by AbhipsaGuru1012** [comment]
@codewithvk can I work on this issue under GSSoC'21?

**Comment by kumarishalini6** [comment]
This  issue got merged , I don't know why it is open yet

**Comment by kumarishalini6** [comment]
@a-abhinav please close this issue

**Comment by kumarishalini6** [comment]
Merged
