### ISSUE TITLE
**Update README file of Assets folder**

### ISSUE THREAD

**Issue by amishaagarwal1998** [girlscript/Girscript-Community-Website#9]
Assets folder will be used to contain all resources of the project - images, designs etc.

**Comment by rutuja2229** [comment]
I am a GSSoC2021 participant can I work on this, plz?
Also, can u give some more detail about what u want this reader file... I am willing to complete this task

**Comment by rebs-becca15** [comment]
Hello @amishaagarwal1998 

I can work on this issue. I am a participant for GSSoC'21 and a content writer by passion. I can help you in completing the readme.md section of the assets folder.
I am really looking forward to making my first contribution to this program.

**Comment by amishaagarwal1998** [comment]
@rebs-becca15 Sure, go ahead!

**Comment by amishaagarwal1998** [comment]
@rutuja2229 It would consist of details of the resources in assets folder. You can proceed.

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?
