### ISSUE TITLE
Social Media Links 

### ISSUE THREAD

**Issue by Sapna2001** [girlscript/Girscript-Community-Website#90]
**Describe the bug**
Adding social media links of Facebook, Twitter, mail

**To Reproduce the Current Behavior**
Steps to reproduce the current behavior:
1. add href in the Link

**Expected behavior**
On click social media page is opened

**Related Screenshots**
Na

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Facebook: https://www.facebook.com/Girlscript
Twitter: https://twitter.com/girlscript1
Mail: community@girlscript.tech

@codewithvk can I work on this?

**Comment by deespider** [comment]
I would like to work on this issue. Please Assign me
